name: Python CI/CD Pipeline

on: [push, pull_request]   # Run on every push or PR

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run Tests
      - name: Run tests
        run: pytest tests

